### ISSUE TITLE
help

### ISSUE THREAD

**Issue by iop3** [darkdarcool/ConsoleHelp#7]
hey @darkdarcool can you help me to make a pip module/package. Not the content just like how you make a module. Thanks!

**Comment by darkdarcool** [comment]
yea, i can.

**Comment by darkdarcool** [comment]
also you messaged me (PDT time) at 11 at night. sry for late response, but I was asleep lol

**Comment by iop3** [comment]
lol ok. so...?

**Comment by darkdarcool** [comment]
So what

**Comment by iop3** [comment]
how to do it

**Comment by darkdarcool** [comment]
[this](https://replit.com/talk/learn/How-to-Make-a-Module-for-Pip/37647) is where I learned

**Comment by iop3** [comment]
alright thanks!

**Comment by darkdarcool** [comment]
your welcome!
